bootstrap_servers: ['localhost:9092']
topic: 'wikimedia_events'
consumer:
  group_id: 'wikimedia_consumer_group'
  auto_offset_reset: 'latest'
  bootstrap_servers: 'localhost:9092'
  consumer_timeout_ms: 5000